
FROM ubuntu:14.04
MAINTAINER Ramesh_bucchappa "ramesh.bucchappa@relevancelab.com"

RUN apt-get update && \
    apt-get --no-install-recommends install -q -y openjdk-7-jre-headless && \
    rm -rf /var/lib/apt/lists/*

ADD http://mirrors.jenkins-ci.org/war/1.651/jenkins.war /opt/jenkins.war
RUN chmod 644 /opt/jenkins.war
ENV JENKINS_HOME /jenkins

ENTRYPOINT ["java", "-jar", "/opt/jenkins.war"]
EXPOSE 8080
CMD [""]
